development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 192.168.3.241                         # VM IP
  port: 4371                                 # VM Port 
  database: store_dbh                          # Database Name
  username: axfvmeun6n0ye9k9                  # User Name
  password: ' afr413rjygbibxbdtx14le5x88m4bj0x'                # Password

