development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 192.168.3.241                         # VM IP
  port: 47519                                 # VM Port 
  database: storage_db                          # Database Name
  username: a43v4cebie40kv0h                  # User Name
  password: 'q5fop3u3ynkq1o2nl67dqwf11kjvbms4'                # Password

